### ISSUE TITLE
Depending on 'trace-and-clarify-if-possible' throws error on Node 8 

### ISSUE THREAD

**Issue by igor-savin-ht** [nknapp/trace-and-clarify-if-possible#3]
Since 'trace' is defined as a dependency in this library, it gets resolved transitively for whoever depends on it, and on Node.js 8 this results in

> error trace@2.4.1: The engine "node" is incompatible with this module. Expected version "^4.5 || ^6.0 || ^7.0".

Probably this can be resolved by changing _trace_ dependency to peerDependency - this will also allow whoever consumes this library to also provide a different major release of trace, that is compatible with Node 8 (if version range would allow >2.x.y version)

**Comment by nknapp** [comment]
Would "optionalDependency" work?

**Comment by nknapp** [comment]
Another option would be a npm "install" script that  installs the correct version of "trace" based on the current node version.

**Comment by igor-savin-ht** [comment]
"If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object"

Worth a shot, I guess :)

**Comment by igor-savin-ht** [comment]
Would npm install script work properly when 'trace-and-clarify-if-possible' is a transitive dependency?

**Comment by nknapp** [comment]
I think so. If not, "postinstall" should work.

**Comment by igor-savin-ht** [comment]
Then it makes sense.

**Comment by igor-savin-ht** [comment]
@nknapp Any chance you could release new version and npm and also new version of bootprint that would depend on it?

**Comment by nknapp** [comment]
I have just release version 1.0.2 which should resolve this problem and some other errors.

**Comment by igor-savin-ht** [comment]
Thanks! I'll give it a spin tomorrow.
